#!/usr/bin/env php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

Yii::setAlias('@zhuravljov/yii/queue', dirname(__DIR__) . '/src');
Yii::setAlias('@zhuravljov/yii/queue/amqp', dirname(__DIR__) . '/src/drivers/amqp');
Yii::setAlias('@zhuravljov/yii/queue/beanstalk', dirname(__DIR__) . '/src/drivers/beanstalk');
Yii::setAlias('@zhuravljov/yii/queue/db', dirname(__DIR__) . '/src/drivers/db');
Yii::setAlias('@zhuravljov/yii/queue/file', dirname(__DIR__) . '/src/drivers/file');
Yii::setAlias('@zhuravljov/yii/queue/gearman', dirname(__DIR__) . '/src/drivers/gearman');
Yii::setAlias('@zhuravljov/yii/queue/redis', dirname(__DIR__) . '/src/drivers/redis');
Yii::setAlias('@zhuravljov/yii/queue/sync', dirname(__DIR__) . '/src/drivers/sync');
Yii::setAlias('@tests', __DIR__);

$config = \yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/app/config/main.php'),
    require(__DIR__ . '/app/config/console.php')
);

$app = new \yii\console\Application($config);
$code = $app->run();
exit($code);
